### ISSUE TITLE
AnEn: Library installation error from R script in stage 2

### ISSUE THREAD

**Issue by vivek-bala** [radical-experiments/entk-experiments#1]
I got the task from the second stage to point where it does not fail due to missing modules or pythonic errors. I get an error from the R script:

1) The R script prompts me asking if I want to install some library. Is it possible to auto install the library as opposed to prompting with a question? We cannot answer question prompts since it cannot be interactive.
2) After the prompts, it fails with an error that it could not install ncdf4.

Please see the error messages below:

```
$ python "evaluation.py" "--file_observation" "/home/whu/data/Temperature_NAM/Analysis_NAM_R.nc" "--file_AnEn" "/home/whu/data/Temperature_NAM/Analysis_NAM_R.nc" "--stations_ID" "[u'0', u'99', u'9900', u'9999', u'1194', u'7953', u'3655', u'9231', u'689', u'9818']" "--test_ID_start" "700.0" "--test_ID_end" "799.0" "--nflts" "8" "--nrows" "100" "--ncols" "100"
Traceback (most recent call last):
  File "evaluation.py", line 27, in <module>
    stations.ID = evaluation.evaluation(    args.file_observation,
AttributeError: 'SignatureTranslatedAnonymousPackage' object has no attribute 'evaluation'
(ve_rpy2)[vivek91@smic1 unit.000001]$ vi evaluation.py 
(ve_rpy2)[vivek91@smic1 unit.000001]$ python "evaluation.py" "--file_observation" "/home/whu/data/Temperature_NAM/Analysis_NAM_R.nc" "--file_AnEn" "/home/whu/data/Temperature_NAM/Analysis_NAM_R.nc" "--stations_ID" "[u'0', u'99', u'9900', u'9999', u'1194', u'7953', u'3655', u'9231', u'689', u'9818']" "--test_ID_start" "700.0" "--test_ID_end" "799.0" "--nflts" "8" "--nrows" "100" "--ncols" "100"
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Loading required package: sp

  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Loading required package: ncdf4

  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Warning in install.packages("ncdf4", repos = "http://cran.us.r-project.org") :
  'lib = "/home/packages/r/3.1.0/INTEL-14.0.2/lib64/R/library"' is not writable

  warnings.warn(x, RRuntimeWarning)
Would you like to use a personal library instead?  (y/n) 
Would you like to create a personal library
~/R/x86_64-unknown-linux-gnu-library/3.1
to install packages into?  (y/n) 
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: trying URL 'http://cran.us.r-project.org/src/contrib/ncdf4_1.16.tar.gz'

  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Content type 'application/x-gzip'
  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning:  length 121420 bytes (118 Kb)

  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: opened URL

  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: =
  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: downloaded 118 Kb


  warnings.warn(x, RRuntimeWarning)
* installing *source* package ‘ncdf4’ ...
** package ‘ncdf4’ successfully unpacked and MD5 sums checked
configure.ac: starting
checking for nc-config... no
-----------------------------------------------------------------------------------
Error, nc-config not found or not executable.  This is a script that comes with the
netcdf library, version 4.1-beta2 or later, and must be present for configuration
to succeed.
 
If you installed the netcdf library (and nc-config) in a standard location, nc-config
should be found automatically.  Otherwise, you can specify the full path and name of
the nc-config script by passing the --with-nc-config=/full/path/nc-config argument
flag to the configure script.  For example:
 
./configure --with-nc-config=/sw/dist/netcdf4/bin/nc-config
 
Special note for R users:
-------------------------
To pass the configure flag to R, use something like this:
 
R CMD INSTALL --configure-args="--with-nc-config=/home/joe/bin/nc-config" ncdf4
 
where you should replace /home/joe/bin etc. with the location where you have
installed the nc-config script that came with the netcdf 4 distribution.
-----------------------------------------------------------------------------------
ERROR: configuration failed for package ‘ncdf4’
* removing ‘/home/vivek91/R/x86_64-unknown-linux-gnu-library/3.1/ncdf4’

The downloaded source packages are in
	‘/tmp/RtmphVYEnZ/downloaded_packages’
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in library(ncdf4) : there is no package called ‘ncdf4’

  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: In addition: 
  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Warning messages:

  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ncdf4’

  warnings.warn(x, RRuntimeWarning)
/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 2: In install.packages("ncdf4", repos = "http://cran.us.r-project.org") :
  installation of package ‘ncdf4’ had non-zero exit status

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "evaluation.py", line 32, in <module>
    args.nrows, args.ncols)
  File "/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in library(ncdf4) : there is no package called ‘ncdf4’

```

**Comment by Weiming-Hu** [comment]
Hi Vivek, thank you for still working on it this late.

For the first question, what is the prompt and what did you do?

For the second question, I think we might need to `module load netcdf/[version that I can't recall for now]`.

Please let me know if this work.

**Comment by vivek-bala** [comment]
So I ran the evaluate.py script on supermic with r loaded and rpy2 installed. The execution started but prompted questions like:

```
Would you like to use a personal library instead?  (y/n) 
Would you like to create a personal library
~/R/x86_64-unknown-linux-gnu-library/3.1
to install packages into?  (y/n)
```

I had to press enter or 'y' to it. Can this be skipped or "auto-answered"?

I loaded the netcdf module. It goes past that error but ends with:
```
Traceback (most recent call last):
  File "evaluation.py", line 32, in <module>
    args.nrows, args.ncols)
  File "/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/home/vivek91/ve_rpy2/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in library(raster) : there is no package called ‘raster’
```

**Comment by Weiming-Hu** [comment]
For the first question, because when installing an R package, by default, it is going to be installed in the `/usr/...` directory which in our case would not work because we don't have permission to write that directory. So we can try to use `destdir=[customized folder]` to tell R to install the package to a different place. I will edit the `evaluate.R` script.

For the second question, I don't have a solution right now. But the error messages basically tells that the package `raster` is not installed. Interestingly, the first two packages, `ncdf4` and `sp`, have been installed, and no message shows up until the third one. So I would say the code works for the first two but fails for the third one. It might be a module load problem. Let's fix it tomorrow.

Thank you!

**Comment by vivek-bala** [comment]
Sure, sounds good! Just wanted to keep you posted.

**Comment by Weiming-Hu** [comment]
I'm cleaning obsolete issues and closing this one. Thank you!
